{
 "title": "Prometheus - SolidFire Node",
 "tags": [
  "solidfire",
  "solidfire_exporter",
  "prometheus"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(solidfire_cluster_active_sessions, sfcluster)"
   },
   {
    "name": "node",
    "label": "node",
    "query": "label_values(solidfire_node_cpu_percentage{sfcluster=~\"$cluster\"}, node_name)"
   },
   { "name": "interval", "label": "Interval", "query": "10m,30m,1h" },
   {
    "name": "drive_status",
    "query": "active,available,erasing,failed,removing"
   },
   { "name": "iscsi_max", "label": "iSCSI Session Threshold", "query": "750" }
  ]
 },
 "panels": [
  { "title": "Node Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$cluster Write IOPS",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(solidfire_node_write_ops_total{sfcluster=~\"$cluster\", node_name=~\"$node\"}[$interval])",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "$cluster Read IOPS",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(solidfire_node_read_ops_total{sfcluster=~\"$cluster\", node_name=~\"$node\"}[$interval])",
     "legendFormat": "{{node_name}} Read"
    }
   ]
  },
  {
   "title": "$node IOPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "repeat": "node",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(solidfire_node_read_ops_total{sfcluster=~\"$cluster\", node_name=~\"$node\"}[$interval])",
     "legendFormat": "{{node_name}} Read"
    },
    {
     "expr": "rate(solidfire_node_write_ops_total{sfcluster=~\"$cluster\", node_name=~\"$node\"}[$interval])",
     "legendFormat": "{{node_name}} Write"
    },
    {
     "expr": "rate(solidfire_node_read_ops_total{sfcluster=~\"$cluster\", node_name=~\"$node\"}[$interval]) + rate(solidfire_node_write_ops_total{sfcluster=~\"$cluster\", node_name=~\"$node\"}[$interval])",
     "legendFormat": "{{node_name}} Total"
    }
   ]
  },
  { "title": "CPU/Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "$node CPU",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 30 },
   "repeat": "node",
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "solidfire_node_cpu_percentage{sfcluster=~\"$cluster\",node_name=~\"$node\"}",
     "legendFormat": "{{node_name}} CPU"
    }
   ]
  },
  {
   "title": "$cluster CPU",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "solidfire_node_cpu_percentage{sfcluster=~\"$cluster\",node_name=~\"$node\"}",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "$cluster Used Memory %",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum by (node_name) (solidfire_node_used_memory_bytes{sfcluster=~\"$cluster\",node_name=~\"$node\"} / 1e+9) / sum by (node_name) (solidfire_node_total_memory_bytes{sfcluster=~\"$cluster\",node_name=~\"$node\"})) * 100",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  { "title": "Drives", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "$drive_status",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4.8, "x": 0, "y": 55 },
   "repeat": "drive_status",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(solidfire_drive_status{sfcluster=~\"$cluster\", node_name=~\"$node\", status=~\"$drive_status\"})",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "$drive_status Drive Capacity",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4.8, "x": 0, "y": 59 },
   "repeat": "drive_status",
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(solidfire_drive_capacity_bytes{sfcluster=~\"$cluster\", node_name=~\"$node\", status=~\"$drive_status\"})"
    }
   ]
  },
  {
   "title": "Drive List",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "solidfire_drive_status{sfcluster=~\"$cluster\", node_name=~\"$node\"}"
    }
   ]
  },
  { "title": "iSCSI Sessions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "$node iSCSI sessions",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 74 },
   "repeat": "node",
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(solidfire_node_iscsi_sessions{sfcluster=~\"$cluster\", node_name=~\"$node\"})  / ($iscsi_max) * 100)"
    }
   ]
  },
  {
   "title": "iSCSI Sessions",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (node_name) (solidfire_node_iscsi_sessions{sfcluster=~\"$cluster\", node_name=~\"$node\"})",
     "legendFormat": "{{node_name}}"
    },
    {
     "expr": "sum(solidfire_node_iscsi_sessions{sfcluster=~\"$cluster\"})",
     "legendFormat": "Total"
    }
   ]
  },
  { "title": "Volumes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 } },
  {
   "title": "Volumes",
   "type": "table",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 89 },
   "targets": [
    {
     "expr": "solidfire_node_iscsi_sessions{sfcluster=~\"$cluster\", node_name=~\"$node\"}"
    }
   ]
  },
  {
   "title": "$cluster Volume movement",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 108 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(solidfire_volume_node_id{sfcluster=~\"$cluster\"}[5m])",
     "legendFormat": "{{volume_name}}"
    }
   ]
  },
  { "title": "Storage Interface", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 121 } },
  {
   "title": "$node storage_bytes_in",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 122 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(solidfire_node_sbytes_in_total{sfcluster=~\"$cluster\"}[$interval])",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "$cluster storage_bytes_out",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 134 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(solidfire_node_sbytes_out_total{sfcluster=~\"$cluster\"}[$interval])",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "$node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 146 },
   "repeat": "node",
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(solidfire_node_sbytes_in_total{sfcluster=~\"$cluster\", node_name=~\"$node\"}[$interval])",
     "legendFormat": "{{node_name}} sbytes_in"
    },
    {
     "expr": "rate(solidfire_node_sbytes_out_total{sfcluster=~\"$cluster\", node_name=~\"$node\"}[$interval])",
     "legendFormat": "{{node_name}} sbytes_out"
    }
   ]
  },
  { "title": "Mgmt Interface", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 154 } },
  {
   "title": "$cluster mgmt bytes in",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 155 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(solidfire_node_mbytes_in_total{sfcluster=~\"$cluster\", node_name=~\"$node\"}[$interval])",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "$cluster mgmt bytes out",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 166 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(solidfire_node_mbytes_out_total{sfcluster=~\"$cluster\", node_name=~\"$node\"}[$interval])",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "$node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 177 },
   "repeat": "node",
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(solidfire_node_mbytes_in_total{sfcluster=~\"$cluster\", node_name=~\"$node\"}[$interval])",
     "legendFormat": "{{node_name}} mbytes_in"
    },
    {
     "expr": "rate(solidfire_node_mbytes_out_total{sfcluster=~\"$cluster\", node_name=~\"$node\"}[$interval])",
     "legendFormat": "{{node_name}} mbytes_out"
    }
   ]
  }
 ]
}