{
 "title": "Prometheus - SolidFire TopK Volumes",
 "tags": [
  "solidfire",
  "solidfire_exporter",
  "prometheus"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(solidfire_cluster_active_sessions, sfcluster)"
   },
   { "name": "interval", "label": "Interval", "query": "10m,30m,1h" },
   { "name": "topk", "query": "5,10,15,20" },
   {
    "name": "bytes_metrics",
    "label": "bytes_metrics",
    "query": "solidfire_volume_read_bytes_total,solidfire_volume_write_bytes_total"
   },
   {
    "name": "latency_metrics",
    "label": "latency_metrics",
    "query": "solidfire_volume_read_latency_seconds,solidfire_volume_write_latency_seconds"
   },
   {
    "name": "ops_metrics",
    "label": "ops_metrics",
    "query": "solidfire_volume_read_ops_total,solidfire_volume_write_ops_total"
   }
  ]
 },
 "panels": [
  { "title": "Read/Write Bytes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Top 5 $bytes_metrics",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "repeat": "bytes_metrics",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "topk($topk,(rate($bytes_metrics{sfcluster=~\"$cluster\"}[$interval])))",
     "legendFormat": "{{volume_name}}"
    },
    {
     "expr": "sum(topk($topk,(rate($bytes_metrics{sfcluster=~\"$cluster\"}[$interval]))))",
     "legendFormat": "sum"
    }
   ]
  },
  { "title": "IOPS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Top 5 $ops_metrics",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
   "repeat": "ops_metrics",
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "topk($topk,(rate($ops_metrics{sfcluster=~\"$cluster\"}[$interval])))",
     "legendFormat": "{{volume_name}}"
    },
    {
     "expr": "sum(topk($topk,(rate($ops_metrics{sfcluster=~\"$cluster\"}[$interval]))))",
     "legendFormat": "sum"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Top 5 $latency_metrics",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 23 },
   "repeat": "latency_metrics",
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "topk($topk,(rate($latency_metrics{sfcluster=~\"$cluster\"}[$interval])))",
     "legendFormat": "{{volume_name}}"
    },
    {
     "expr": "sum(topk($topk,(rate($latency_metrics{sfcluster=~\"$cluster\"}[$interval]))))",
     "legendFormat": "sum"
    }
   ]
  }
 ]
}