{
 "title": "Prometheus - SolidFire Cluster",
 "tags": [
  "solidfire",
  "prometheus",
  "solidfire_exporter"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(solidfire_cluster_capacity_active_sessions, sfcluster)"
   },
   {
    "name": "node",
    "label": "node",
    "query": "label_values(solidfire_node_stats_cpu_percentage{sfcluster=~\"$cluster\"}, node_name)"
   },
   { "name": "interval", "label": "Interval", "query": "10m,30m,1h" }
  ]
 },
 "panels": [
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Warnings",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(solidfire_cluster_active_faults{sfcluster=~\"$cluster\",severity=\"warning\"})"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(solidfire_cluster_active_faults{sfcluster=~\"$cluster\",severity=\"error\"})"
    }
   ]
  },
  {
   "title": "Fault History",
   "type": "graph",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(severity) (solidfire_cluster_active_faults{sfcluster=~\"$cluster\"})",
     "legendFormat": "{{sfcluster}} {{severity}}"
    }
   ]
  },
  {
   "title": "Critical",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(solidfire_cluster_active_faults{sfcluster=~\"$cluster\",severity=\"critical\"})"
    }
   ]
  },
  {
   "title": "Best Practice",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(solidfire_cluster_active_faults{sfcluster=~\"$cluster\",severity=\"bestpractice\"})"
    }
   ]
  },
  {
   "title": "Fault History",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": " (solidfire_cluster_active_faults{sfcluster=~\"$cluster\",severity=\"warning\"}) OR (solidfire_cluster_active_faults{sfcluster=~\"$cluster\",severity=\"error\"} + 1)"
    }
   ]
  },
  { "title": "Storage Efficiency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Block Capacity Fullness",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(solidfire_cluster_block_fullness{level=~\"stage1Happy|stage2Aware\",sfcluster=~\"$cluster\"}) "
    }
   ]
  },
  {
   "title": "Thin Provisioning Factor",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(solidfire_cluster_capacity_thin_provisioning_factor{sfcluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Efficiency Factor",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(solidfire_cluster_capacity_efficiency_factor{sfcluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Provisioned Capacity All Clusters",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 13 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(solidfire_cluster_capacity_provisioned_space_bytes{}) ",
     "legendFormat": "{{sfcluster}} Provisioned Space"
    }
   ]
  },
  {
   "title": "Metadata Capacity Fullness",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(solidfire_cluster_metadata_fullness{level=~\"stage1Happy|stage2Aware\",sfcluster=~\"$cluster\"}) "
    }
   ]
  },
  {
   "title": "Compression Factor",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "solidfire_cluster_capacity_compression_factor{sfcluster=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Deduplication Factor",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(solidfire_cluster_capacity_de_duplication_factor{sfcluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Capacity",
   "type": "graph",
   "description": "NOTE: Need to use `GetClusterFullThreshold` API call to match whats on the SF GUI. \n\n",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "bytes", "label": "Terabytes" }
   ],
   "targets": [
    {
     "expr": "solidfire_cluster_capacity_max_used_space_bytes{sfcluster=~\"$cluster\"}",
     "legendFormat": "{{sfcluster}} Max Usable Space"
    },
    {
     "expr": "(solidfire_cluster_capacity_unique_blocks_used_space_bytes{sfcluster=~\"$cluster\"})",
     "legendFormat": "{{sfcluster}} Used Capacity"
    },
    {
     "expr": "(solidfire_cluster_capacity_provisioned_space_bytes{sfcluster=~\"$cluster\"}) ",
     "legendFormat": "{{sfcluster}} Provisioned Space"
    }
   ]
  },
  {
   "title": "Licensed Capacity",
   "type": "graph",
   "description": "NOTE: Need to use `GetClusterFullThreshold` API call to match whats on the SF GUI. \n\n",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "decbytes", "label": "Terabytes" }
   ],
   "targets": [
    {
     "expr": "(sum(solidfire_cluster_capacity_provisioned_space_bytes))",
     "legendFormat": "Total Provisioned Space"
    }
   ]
  },
  { "title": "Cluster Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Sessions",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 27 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "solidfire_cluster_capacity_active_sessions{sfcluster=~\"$cluster\"}",
     "legendFormat": "active sessions"
    }
   ]
  },
  {
   "title": "$cluster CPU",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 27 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(solidfire_node_stats_cpu_percentage{sfcluster=~\"$cluster\"})",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Cluster Read %",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 27 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(solidfire_cluster_stats_read_ops_total{sfcluster=~\"$cluster\"}) /  (solidfire_cluster_stats_read_ops_total{sfcluster=~\"$cluster\"} + solidfire_cluster_stats_write_ops_total{sfcluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Cluster Write %",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 27 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "solidfire_cluster_stats_write_ops_total{sfcluster=~\"$cluster\"} / (solidfire_cluster_stats_read_ops_total{sfcluster=~\"$cluster\"} + solidfire_cluster_stats_write_ops_total{sfcluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "$cluster CPU",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "solidfire_node_stats_cpu_percentage{sfcluster=~\"$cluster\"}",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Performance  Utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "solidfire_cluster_stats_throughput_utilization{sfcluster=~\"$cluster\"}",
     "legendFormat": "{{sfcluster}} Utilization"
    }
   ]
  },
  {
   "title": "$cluster IOPS",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "sum by (sfcluster) (rate(solidfire_node_stats_read_ops{sfcluster=~\"$cluster\", node_name=~\"$node\"}[$interval]))",
     "legendFormat": "{{sfcluster}} Reads"
    },
    {
     "expr": "sum by (sfcluster) (rate(solidfire_node_stats_write_ops{sfcluster=~\"$cluster\", node_name=~\"$node\"}[$interval]))",
     "legendFormat": "{{sfcluster}} Writes"
    },
    {
     "expr": "sum by (sfcluster) (rate(solidfire_node_stats_read_ops{sfcluster=~\"$cluster\", node_name=~\"$node\"}[$interval])) + sum by (sfcluster) (rate(solidfire_node_stats_write_ops{sfcluster=~\"$cluster\", node_name=~\"$node\"}[$interval]))",
     "legendFormat": "{{sfcluster}} Total"
    },
    {
     "expr": "solidfire_cluster_capacity_cluster_recent_io_size_bytes{sfcluster=~\"$cluster\"}",
     "legendFormat": "{{sfcluster}} IO Size"
    }
   ]
  },
  {
   "title": "$cluster Read/Write Bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(solidfire_cluster_stats_read_bytes_total{sfcluster=~\"$cluster\"}[$interval])",
     "legendFormat": "{{sfcluster}} Read"
    },
    {
     "expr": "irate(solidfire_cluster_stats_write_bytes_total{sfcluster=~\"$cluster\"}[$interval])",
     "legendFormat": "{{sfcluster}} Write"
    },
    {
     "expr": "irate(solidfire_cluster_stats_read_bytes_total{sfcluster=~\"$cluster\"}[$interval]) + irate(solidfire_cluster_stats_write_bytes_total{sfcluster=~\"$cluster\"}[$interval])",
     "legendFormat": "{{sfcluster}} Total"
    }
   ]
  },
  {
   "title": "Queue Depth",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solidfire_cluster_stats_client_queue_depth{sfcluster=~\"$cluster\"}",
     "legendFormat": "{{sfcluster}} queue depth"
    }
   ]
  }
 ]
}