{
 "title": "Prometheus - SolidFire Volume",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(solidfire_cluster_capacity_active_sessions, sfcluster)"
   },
   {
    "name": "volume",
    "label": "volume",
    "query": "label_values(solidfire_volume_stats_actual_iops{sfcluster=~\"^$cluster\"},volume_name)"
   },
   {
    "name": "solidfire_volume_qos_histogram",
    "label": "QoS Histogram",
    "query": "metrics(solidfire_volume_qos.*bucket)"
   },
   { "name": "interval", "label": "Interval", "query": "1m,2m,5m,1h" }
  ]
 },
 "panels": [
  { "title": "Volume Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Volume Size",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(solidfire_volume_stats_size{sfcluster=~\"$cluster\", volume_name=~\"$volume\"})"
    }
   ]
  },
  {
   "title": "Average Utilization %",
   "type": "singlestat",
   "description": "A floating value that describes\nhow much the client is using the\nvolume. \n\nPossible values:\n\n• 0: The client is not using the\nvolume.\n\n• 100: The client is using their\nmaximum.\n\n• gt 100% : The client is using their\nburst.",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(solidfire_volume_stats_utilization{sfcluster=~\"$cluster\", volume_name=~\"$volume\"}) * 100"
    }
   ]
  },
  {
   "title": "Capacity Utilization",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(solidfire_volume_stats_non_zero_blocks{sfcluster=~\"$cluster\", volume_name=~\"$volume\"}) / sum(solidfire_volume_stats_size{sfcluster=~\"$cluster\", volume_name=~\"$volume\"})* 4096 * 100"
    }
   ]
  },
  {
   "title": "Last %Read",
   "type": "singlestat",
   "description": "The percentage read\noperations during the last sample\nperiod",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(solidfire_volume_stats_read_ops_last_sample {sfcluster=~\"$cluster\", volume_name=~\"$volume\"}) / sum((solidfire_volume_stats_read_ops_last_sample{sfcluster=~\"$cluster\", volume_name=~\"$volume\"} +  solidfire_volume_stats_write_ops_last_sample{sfcluster=~\"$cluster\", volume_name=~\"$volume\"})) * 100"
    }
   ]
  },
  {
   "title": "Last %Write",
   "type": "singlestat",
   "description": "The percentage of write\noperations during the last sample\nperiod.",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(solidfire_volume_stats_write_ops_last_sample{sfcluster=~\"$cluster\", volume_name=~\"$volume\"}) / sum((solidfire_volume_stats_read_ops_last_sample{sfcluster=~\"$cluster\", volume_name=~\"$volume\"} +  solidfire_volume_stats_write_ops_last_sample{sfcluster=~\"$cluster\", volume_name=~\"$volume\"})) * 100"
    }
   ]
  },
  {
   "title": "Overall %Read",
   "type": "singlestat",
   "description": "The total read operations percentage to the\nvolume since the creation of the\nvolume.",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(solidfire_volume_stats_read_ops {sfcluster=~\"$cluster\", volume_name=~\"$volume\"}) / sum((solidfire_volume_stats_read_ops{sfcluster=~\"$cluster\", volume_name=~\"$volume\"} +  solidfire_volume_stats_write_ops{sfcluster=~\"$cluster\", volume_name=~\"$volume\"})) * 100"
    }
   ]
  },
  {
   "title": "Overall %Write",
   "type": "singlestat",
   "description": "The total cumulative write\noperations percentage to the volume since\nthe creation of the volume.",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(solidfire_volume_stats_write_ops{sfcluster=~\"$cluster\", volume_name=~\"$volume\"}) / sum((solidfire_volume_stats_read_ops{sfcluster=~\"$cluster\", volume_name=~\"$volume\"} +  solidfire_volume_stats_write_ops{sfcluster=~\"$cluster\", volume_name=~\"$volume\"})) * 100"
    }
   ]
  },
  {
   "title": "Total Volume iSCSI Sessions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (volume_name) (solidfire_node_iscsi_sessions_total{sfcluster=~\"$cluster\", volume_name=~\"$volume\"})",
     "legendFormat": "{{volume_name}}"
    }
   ]
  },
  {
   "title": "solidfire_volume_stats_latency_usec",
   "type": "graph",
   "description": "The average time, in\nmicroseconds, to complete\noperations to the volume in the\nlast 500 milliseconds. A \"0\"\n(zero) value means there is no\nI/O to the volume.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "solidfire_volume_stats_latency_usec{sfcluster=~\"$cluster\", volume_name=~\"$volume\"}",
     "legendFormat": "{{ volume_name }}"
    }
   ]
  },
  {
   "title": "solidfire_volume_stats_read/write_bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (volume_name) (rate(solidfire_volume_stats_read_bytes {sfcluster=~\"$cluster\", volume_name=~\"$volume\"}[$interval]))",
     "legendFormat": "{{ volume_name }} read  bytes"
    },
    {
     "expr": "sum by (volume_name) (rate(solidfire_volume_stats_write_bytes {sfcluster=~\"$cluster\", volume_name=~\"$volume\"}[$interval]))",
     "legendFormat": "{{ volume_name }} write  bytes"
    }
   ]
  },
  {
   "title": "solidfire_volume_stats_utilization",
   "type": "graph",
   "description": "A floating value that describes\nhow much the client is using the\nvolume. Possible values:\n\n- 0: The client is not using the\nvolume.\n\n- 100: The client is using their\nmaximum.\n\n - gt 100: The client is using their\nburst.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "solidfire_volume_stats_utilization{sfcluster=~\"$cluster\", volume_name=~\"$volume\"} * 100",
     "legendFormat": "{{ volume_name }}"
    }
   ]
  },
  {
   "title": "solidfire_volume_stats_burst_iops_credit",
   "type": "graph",
   "description": "The total number of IOP credits\navailable to the user. When\nvolumes are not using up to the\nconfigured maxIOPS, credits are\naccrued.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "solidfire_volume_stats_burst_iops_credit{sfcluster=~\"$cluster\", volume_name=~\"$volume\"}",
     "legendFormat": "{{ volume_name }}"
    }
   ]
  },
  {
   "title": "solidfire_volume_stats_average_iop_size",
   "type": "graph",
   "description": "The average size in bytes of\nrecent I/O to the volume in the\nlast 500 milliseconds.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "solidfire_volume_stats_average_iop_size{sfcluster=~\"$cluster\", volume_name=~\"$volume\"}",
     "legendFormat": "{{ volume_name }} iops size"
    }
   ]
  },
  {
   "title": "solidfire_volume_stats_actual_iops",
   "type": "graph",
   "description": "The current actual IOPS to the\nvolume in the last 500\nmilliseconds.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "solidfire_volume_stats_actual_iops{sfcluster=~\"$cluster\", volume_name=~\"$volume\"}",
     "legendFormat": "{{ volume_name }} actual  iops"
    }
   ]
  },
  {
   "title": "solidfire_volume_stats_read/write_latency_usec",
   "type": "graph",
   "description": "The average time, in\nmicroseconds, to complete read\noperations to the volume in the\nlast 500 milliseconds",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "solidfire_volume_stats_read_latency_usec{sfcluster=~\"$cluster\", volume_name=~\"$volume\"}",
     "legendFormat": "{{volume_name}} read latency"
    },
    {
     "expr": "solidfire_volume_stats_write_latency_usec{sfcluster=~\"$cluster\", volume_name=~\"$volume\"}",
     "legendFormat": "{{volume_name}} write latency"
    }
   ]
  },
  {
   "title": "solidfire_volume_stats_client_queue_depth",
   "type": "graph",
   "description": "The number of outstanding read\nand write operations to the\nvolume.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "solidfire_volume_stats_client_queue_depth{sfcluster=~\"$cluster\", volume_name=~\"$volume\"}",
     "legendFormat": "{{ volume_name }}"
    }
   ]
  },
  {
   "title": "solidfire_volume_stats_unaligned_reads/writes",
   "type": "graph",
   "description": "The total cumulative unaligned\nread operations to a volume\nsince the creation of the volume.\n\nThe total cumulative unaligned\nwrite operations to a volume\nsince the creation of the volume",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "increase(solidfire_volume_stats_unaligned_reads{sfcluster=~\"$cluster\", volume_name=~\"$volume\"}[$interval])",
     "legendFormat": "{{ volume_name }} unaligned  reads"
    },
    {
     "expr": "increase(solidfire_volume_stats_unaligned_writes{sfcluster=~\"$cluster\", volume_name=~\"$volume\"}[$interval])",
     "legendFormat": "{{ volume_name }} unaligned writes"
    }
   ]
  },
  {
   "title": "solidfire_volume_stats_throttle",
   "type": "graph",
   "description": "A floating value between 0 and 1\nthat represents how much the\nsystem is throttling clients below\ntheir maxIOPS because of rereplication of data, transient\nerrors, and snapshots taken",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "solidfire_volume_stats_throttle{sfcluster=~\"$cluster\", volume_name=~\"$volume\"}",
     "legendFormat": "{{ volume_name }}"
    }
   ]
  },
  {
   "title": "$volume Volume QoS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "repeat": "volume",
   "collapsed": true,
   "panels": [
    {
     "title": "[[volume]]_[[solidfire_volume_qos_histogram]]",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "repeat": "solidfire_volume_qos_histogram",
     "targets": [
      {
       "expr": "sum by(le, volume_name) (increase($solidfire_volume_qos_histogram{sfcluster=~\"^$cluster\",volume_name=~\"$volume\"}[$interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "[[volume]]_[[solidfire_volume_qos_histogram]]",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "targets": [
      {
       "expr": "sum by(le, volume_name) (increase($solidfire_volume_qos_histogram{sfcluster=~\"^$cluster\",volume_name=~\"$volume\"}[$interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "[[volume]]_[[solidfire_volume_qos_histogram]]",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "targets": [
      {
       "expr": "sum by(le, volume_name) (increase($solidfire_volume_qos_histogram{sfcluster=~\"^$cluster\",volume_name=~\"$volume\"}[$interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "[[volume]]_[[solidfire_volume_qos_histogram]]",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "targets": [
      {
       "expr": "sum by(le, volume_name) (increase($solidfire_volume_qos_histogram{sfcluster=~\"^$cluster\",volume_name=~\"$volume\"}[$interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "[[volume]]_[[solidfire_volume_qos_histogram]]",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "sum by(le, volume_name) (increase($solidfire_volume_qos_histogram{sfcluster=~\"^$cluster\",volume_name=~\"$volume\"}[$interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "[[volume]]_[[solidfire_volume_qos_histogram]]",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "targets": [
      {
       "expr": "sum by(le, volume_name) (increase($solidfire_volume_qos_histogram{sfcluster=~\"^$cluster\",volume_name=~\"$volume\"}[$interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  }
 ]
}