{
 "title": "Fault Summary",
 "panels": [
  {
   "title": "BESTPRACTICE",
   "type": "singlestat",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(solidfire_cluster_active_faults{sfcluster=~\"$sfcluster\",severity=\"bestpractice\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "WARNING",
   "type": "singlestat",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(solidfire_cluster_active_faults{sfcluster=~\"$sfcluster\",severity=\"warning\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "ERRORS",
   "type": "singlestat",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(solidfire_cluster_active_faults{sfcluster=~\"$sfcluster\",severity=\"errors\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "CRITICAL",
   "type": "singlestat",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(solidfire_cluster_active_faults{sfcluster=~\"$sfcluster\",severity=\"critical\"}) or vector(0)"
    }
   ]
  }
 ]
}
{
 "title": "Fault Detail",
 "panels": [
  {
   "title": "Faults",
   "type": "table",
   "targets": [
    {
     "expr": "solidfire_cluster_active_faults{sfcluster=~\"$sfcluster\"} > 0"
    }
   ]
  }
 ]
}
{
 "title": "Storage Capacity",
 "panels": [
  {
   "title": "THIN PROVISIONING FACTOR",
   "type": "singlestat",
   "valueName": "avg",
   "targets": [
    {
     "expr": "solidfire_cluster_thin_provisioning_factor{sfcluster=~\"$sfcluster\"}"
    }
   ]
  },
  {
   "title": "EFFICIENCY FACTOR",
   "type": "singlestat",
   "valueName": "avg",
   "targets": [
    {
     "expr": "solidfire_cluster_efficiency_factor{sfcluster=~\"$sfcluster\"}"
    }
   ]
  },
  {
   "title": "COMPRESSION FACTOR",
   "type": "singlestat",
   "valueName": "avg",
   "targets": [
    {
     "expr": "solidfire_cluster_compression_factor{sfcluster=~\"$sfcluster\"}"
    }
   ]
  },
  {
   "title": "DEDUPLICATION FACTOR",
   "type": "singlestat",
   "valueName": "avg",
   "targets": [
    {
     "expr": "solidfire_cluster_de_duplication_factor{sfcluster=~\"$sfcluster\"}"
    }
   ]
  },
  {
   "title": "Capacity",
   "type": "graph",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "solidfire_cluster_max_used_space_bytes{sfcluster=~\"$sfcluster\"}",
     "legendFormat": "{{sfcluster}} - Max Usable Capacity"
    },
    {
     "expr": "solidfire_cluster_unique_blocks_used_space_bytes{sfcluster=~\"$sfcluster\"}",
     "legendFormat": "{{sfcluster}} - Unique Blocks Space Used"
    },
    {
     "expr": "solidfire_cluster_provisioned_space_bytes{sfcluster=~\"$sfcluster\"}",
     "legendFormat": "{{sfcluster}} - Provisioned Space"
    }
   ]
  }
 ]
}
{
 "title": "Cluster Performance",
 "panels": [
  {
   "title": "Cpu Usage",
   "type": "graph",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "solidfire_node_cpu_percentage{sfcluster=~\"$sfcluster\"}",
     "legendFormat": "{{sfcluster}} - {{node_name}}"
    }
   ]
  },
  {
   "title": "Performance Utilization",
   "type": "graph",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "solidfire_cluster_throughput_utilization{sfcluster=~\"$sfcluster\"} * 100",
     "legendFormat": "{{sfcluster}}"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "graph",
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "sum by (sfcluster) (rate(solidfire_node_read_ops_total{sfcluster=~\"$sfcluster\"}[$interval]))",
     "legendFormat": "{{sfcluster}} read iops"
    },
    {
     "expr": "sum by (sfcluster) (rate(solidfire_node_write_ops_total{sfcluster=~\"$sfcluster\"}[$interval]))",
     "legendFormat": "{{sfcluster}} write iops"
    },
    {
     "expr": "sum by (sfcluster) (rate(solidfire_node_read_ops_total{sfcluster=~\"$sfcluster\"}[$interval])) + sum by (sfcluster) (rate(solidfire_node_write_ops_total{sfcluster=~\"$sfcluster\"}[$interval]))",
     "legendFormat": "{{sfcluster}} total iops"
    }
   ]
  },
  {
   "title": "Throughput/s",
   "type": "graph",
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (sfcluster) (rate(solidfire_cluster_read_bytes_total{sfcluster=~\"$sfcluster\"}[$interval]))",
     "legendFormat": "{{sfcluster}} read bytes"
    },
    {
     "expr": "sum by (sfcluster) (rate(solidfire_cluster_write_bytes_total{sfcluster=~\"$sfcluster\"}[$interval]))",
     "legendFormat": "{{sfcluster}} write bytes"
    },
    {
     "expr": "sum by (sfcluster) (rate(solidfire_cluster_read_bytes_total{sfcluster=~\"$sfcluster\"}[$interval])) + sum by (sfcluster) (rate(solidfire_cluster_write_bytes_total{sfcluster=~\"$sfcluster\"}[$interval]))",
     "legendFormat": "{{sfcluster}} total bytes"
    }
   ]
  },
  {
   "title": "iSCSI Sessions",
   "type": "graph",
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "sum by (sfcluster) (solidfire_cluster_active_sessions{sfcluster=~\"$sfcluster\"})",
     "legendFormat": "{{sfcluster }} sessions"
    }
   ]
  },
  {
   "title": "Queue Depth",
   "type": "graph",
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "sum by (sfcluster) (solidfire_cluster_client_queue_depth{sfcluster=~\"$sfcluster\"})",
     "legendFormat": "{{sfcluster}} queue depth"
    }
   ]
  }
 ]
}