{
 "title": "Node Performance Summary - $node",
 "panels": [
  {
   "title": "CPU USAGE",
   "type": "singlestat",
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "solidfire_node_cpu_percentage{sfcluster=~\"$sfcluster\",node_name=~\"$node\"}"
    }
   ]
  },
  {
   "title": "MEMORY USAGE",
   "type": "singlestat",
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "solidfire_node_used_memory_bytes{sfcluster=~\"$sfcluster\",node_name=~\"$node\"} / \n\t\t\t\t\tsolidfire_node_total_memory_bytes{sfcluster=~\"$sfcluster\",node_name=~\"$node\"} * 100"
    }
   ]
  },
  {
   "title": "ISCSI SESSIONS",
   "type": "singlestat",
   "valueName": "current",
   "targets": [
    {
     "expr": "solidfire_node_iscsi_sessions{sfcluster=~\"$sfcluster\", node_name=~\"$node\"}"
    }
   ]
  },
  {
   "title": "MGMT BANDWIDTH",
   "type": "singlestat",
   "description": "Bytes i/o on management network interface",
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(solidfire_node_interface_in_bytes_total{interface=\"management\",sfcluster=~\"$sfcluster\",node_name=~\"$node\"}[$interval]) +\n\t\t\t\t\trate(solidfire_node_interface_out_bytes_total{interface=\"management\",sfcluster=~\"$sfcluster\",node_name=~\"$node\"}[$interval])"
    }
   ]
  },
  {
   "title": "STORAGE BANDWIDTH",
   "type": "singlestat",
   "description": "Bytes i/o on storage network interface",
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(solidfire_node_interface_in_bytes_total{interface=\"storage\",sfcluster=~\"$sfcluster\",node_name=~\"$node\"}[$interval]) +\n\t\t\t\t\trate(solidfire_node_interface_out_bytes_total{interface=\"storage\",sfcluster=~\"$sfcluster\",node_name=~\"$node\"}[$interval])"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "singlestat",
   "format": "iops",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(solidfire_node_read_ops_total{sfcluster=~\"$sfcluster\", node_name=~\"$node\"}[$interval]) +\n\t\t\t\t\trate(solidfire_node_write_ops_total{sfcluster=~\"$sfcluster\", node_name=~\"$node\"}[$interval])"
    }
   ]
  }
 ]
}
{
 "title": "Node Drive Summary - $node",
 "panels": [
  {
   "title": "ACTIVE",
   "type": "singlestat",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(solidfire_drive_status{sfcluster=~\"$sfcluster\",node_name=~\"$node\",status=\"active\"}) by (node_name)"
    }
   ]
  },
  {
   "title": "AVAILABLE",
   "type": "singlestat",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(solidfire_drive_status{sfcluster=~\"$sfcluster\",node_name=~\"$node\",status=\"available\"}) by (node_name)"
    }
   ]
  },
  {
   "title": "REMOVING",
   "type": "singlestat",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(solidfire_drive_status{sfcluster=~\"$sfcluster\",node_name=~\"$node\",status=\"removing\"}) by (node_name)"
    }
   ]
  },
  {
   "title": "FAILED",
   "type": "singlestat",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(solidfire_drive_status{sfcluster=~\"$sfcluster\",node_name=~\"$node\",status=\"failed\"}) by (node_name)"
    }
   ]
  },
  {
   "title": "ERASING",
   "type": "singlestat",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(solidfire_drive_status{sfcluster=~\"$sfcluster\",node_name=~\"$node\",status=\"erasing\"}) by (node_name)"
    }
   ]
  }
 ]
}
{
 "title": "Node Performance Detail",
 "panels": [
  {
   "title": "CPU",
   "type": "graph",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "solidfire_node_cpu_percentage{sfcluster=~\"$sfcluster\", node_name=~\"$node\"}",
     "legendFormat": "{{node_name}} - cpu usage"
    }
   ]
  },
  {
   "title": "MEMORY",
   "type": "graph",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "solidfire_node_used_memory_bytes{sfcluster=~\"$sfcluster\",node_name=~\"$node\"} / \n\t\t\t\t\tsolidfire_node_total_memory_bytes{sfcluster=~\"$sfcluster\",node_name=~\"$node\"} * 100",
     "legendFormat": "{{node_name}} - memory usage"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "graph",
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "rate(solidfire_node_read_ops_total{sfcluster=~\"$sfcluster\", node_name=~\"$node\"}[$interval])",
     "legendFormat": "{{node_name}} - read iops"
    },
    {
     "expr": "rate(solidfire_node_write_ops_total{sfcluster=~\"$sfcluster\", node_name=~\"$node\"}[$interval])",
     "legendFormat": "{{node_name}} - write iops"
    },
    {
     "expr": "rate(solidfire_node_read_ops_total{sfcluster=~\"$sfcluster\", node_name=~\"$node\"}[$interval]) +\n\t\t\t\t\trate(solidfire_node_write_ops_total{sfcluster=~\"$sfcluster\", node_name=~\"$node\"}[$interval])",
     "legendFormat": "{{node_name}} - total iops"
    }
   ]
  },
  {
   "title": "ISCSI SESSIONS",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solidfire_node_iscsi_sessions{sfcluster=~\"$sfcluster\", node_name=~\"$node\"}",
     "legendFormat": "{{node_name}} - {{volume_name}} sessions"
    },
    {
     "expr": "sum(solidfire_node_iscsi_sessions{sfcluster=~\"$sfcluster\", node_name=~\"$node\"}) by (node_name)",
     "legendFormat": "{{node_name}} - total"
    }
   ]
  }
 ]
}
{
 "title": "Node Throughput Detail",
 "panels": [
  {
   "title": "MGMT IFACE THROUGHPUT ",
   "type": "graph",
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(solidfire_node_interface_in_bytes_total{sfcluster=~\"$sfcluster\", node_name=~\"$node\", interface=\"management\"}[$interval])",
     "legendFormat": "{{node_name}} - in"
    },
    {
     "expr": "rate(solidfire_node_interface_out_bytes_total{sfcluster=~\"$sfcluster\", node_name=~\"$node\", interface=\"management\"}[$interval])",
     "legendFormat": "{{node_name}} - out"
    },
    {
     "expr": "rate(solidfire_node_interface_in_bytes_total{sfcluster=~\"$sfcluster\", node_name=~\"$node\", interface=\"management\"}[$interval]) +\n\t\t\t\t\trate(solidfire_node_interface_out_bytes_total{sfcluster=~\"$sfcluster\", node_name=~\"$node\", interface=\"management\"}[$interval])",
     "legendFormat": "{{node_name}} - total"
    }
   ]
  },
  {
   "title": "STORAGE IFACE THROUGHPUT ",
   "type": "graph",
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(solidfire_node_interface_in_bytes_total{sfcluster=~\"$sfcluster\", node_name=~\"$node\", interface=\"storage\"}[$interval])",
     "legendFormat": "{{node_name}} - in"
    },
    {
     "expr": "rate(solidfire_node_interface_out_bytes_total{sfcluster=~\"$sfcluster\", node_name=~\"$node\", interface=\"storage\"}[$interval])",
     "legendFormat": "{{node_name}} - out"
    },
    {
     "expr": "rate(solidfire_node_interface_in_bytes_total{sfcluster=~\"$sfcluster\", node_name=~\"$node\", interface=\"storage\"}[$interval]) +\n\t\t\t\t\trate(solidfire_node_interface_out_bytes_total{sfcluster=~\"$sfcluster\", node_name=~\"$node\", interface=\"storage\"}[$interval])",
     "legendFormat": "{{node_name}} - total"
    }
   ]
  }
 ]
}