{
 "title": "Volume Summary - $volume",
 "panels": [
  {
   "title": "VOLUME SIZE",
   "type": "singlestat",
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "solidfire_volume_size_bytes{sfcluster=~\"$sfcluster\", volume_name=~\"$volume\"}"
    }
   ]
  },
  {
   "title": "VOLUME BLOCK UTILIZATION",
   "type": "singlestat",
   "description": "Percentage of nonzero blocks (This is the closest measurement we have to 'volume fullness')",
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "solidfire_volume_non_zero_blocks{sfcluster=~\"$sfcluster\", volume_name=~\"$volume\"} / \n\t\t\t\t\t(solidfire_volume_zero_blocks{sfcluster=~\"$sfcluster\", volume_name=~\"$volume\"} + \n\t\t\t\t\tsolidfire_volume_non_zero_blocks{sfcluster=~\"$sfcluster\", volume_name=~\"$volume\"}) * 100"
    }
   ]
  },
  {
   "title": "VOLUME THROUGHPUT UTILIZATION",
   "type": "singlestat",
   "description": "How much of the volume's throughput capacity (IOPS) is being utilized",
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "solidfire_volume_utilization{sfcluster=~\"$sfcluster\", volume_name=~\"$volume\"} * 100"
    }
   ]
  },
  {
   "title": "ISCSI SESSIONS",
   "type": "singlestat",
   "description": "Number of ISCSI sessions to the volume",
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "solidfire_node_iscsi_sessions{sfcluster=~\"$sfcluster\", volume_name=~\"$volume\"}"
    }
   ]
  },
  {
   "title": "OVERALL READ %",
   "type": "singlestat",
   "description": "The total read operations percentage to the volume since the creation of the volume.",
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "solidfire_volume_read_ops_total{sfcluster=~\"$sfcluster\", volume_name=~\"$volume\"} /\n\t\t\t\t\t(solidfire_volume_read_ops_total{sfcluster=~\"$sfcluster\", volume_name=~\"$volume\"} + \n\t\t\t\t\t\tsolidfire_volume_write_ops_total{sfcluster=~\"$sfcluster\", volume_name=~\"$volume\"}) * 100"
    }
   ]
  },
  {
   "title": "OVERALL WRITE %",
   "type": "singlestat",
   "description": "The total write operations percentage to the volume since the creation of the volume.",
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "solidfire_volume_write_ops_total{sfcluster=~\"$sfcluster\", volume_name=~\"$volume\"} /\n\t\t\t\t\t(solidfire_volume_read_ops_total{sfcluster=~\"$sfcluster\", volume_name=~\"$volume\"} + \n\t\t\t\t\t\tsolidfire_volume_write_ops_total{sfcluster=~\"$sfcluster\", volume_name=~\"$volume\"}) * 100"
    }
   ]
  }
 ]
}
{
 "title": "Volume Detail",
 "panels": [
  {
   "title": "VOLUME CAPACITY",
   "type": "graph",
   "description": "Volume nonzero blocks / (nonzero blocks + zero blocks)",
   "yaxes": [
    { "format": "short", "label": "blocks" }
   ],
   "targets": [
    {
     "expr": "solidfire_volume_non_zero_blocks{sfcluster=~\"$sfcluster\", volume_name=~\"$volume\"}",
     "legendFormat": "{{volume_name}} - Non-Zero Blocks"
    },
    {
     "expr": "solidfire_volume_zero_blocks{sfcluster=~\"$sfcluster\", volume_name=~\"$volume\"}",
     "legendFormat": "{{volume_name}} - Zero Blocks"
    }
   ]
  },
  {
   "title": "ISCSI SESSIONS",
   "type": "graph",
   "description": "Number of ISCSI sessions to the volume",
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "solidfire_node_iscsi_sessions{sfcluster=~\"$sfcluster\", volume_name=~\"$volume\"}",
     "legendFormat": "{{volume_name}} - ISCSI Sessions"
    }
   ]
  }
 ]
}
{
 "title": "Volume Performance",
 "panels": [
  {
   "title": "VOLUME LATENCY",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(solidfire_volume_read_latency_seconds_total{sfcluster=~\"$sfcluster\", volume_name=~\"$volume\"}[$interval])",
     "legendFormat": "{{volume_name}} - read latency"
    },
    {
     "expr": "rate(solidfire_volume_write_latency_seconds_total{sfcluster=~\"$sfcluster\", volume_name=~\"$volume\"}[$interval])",
     "legendFormat": "{{volume_name}} - write latency"
    }
   ]
  },
  {
   "title": "VOLUME THROUGHPUT",
   "type": "graph",
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(solidfire_volume_read_bytes_total{sfcluster=~\"$sfcluster\", volume_name=~\"$volume\"}[$interval])",
     "legendFormat": "{{volume_name}} - read bytes"
    },
    {
     "expr": "rate(solidfire_volume_write_bytes_total{sfcluster=~\"$sfcluster\", volume_name=~\"$volume\"}[$interval])",
     "legendFormat": "{{volume_name}} - write bytes"
    },
    {
     "expr": "rate(solidfire_volume_read_bytes_total{sfcluster=~\"$sfcluster\", volume_name=~\"$volume\"}[$interval]) +\n\t\t\t\t\trate(solidfire_volume_write_bytes_total{sfcluster=~\"$sfcluster\", volume_name=~\"$volume\"}[$interval])",
     "legendFormat": "{{volume_name}} - total bytes"
    }
   ]
  },
  {
   "title": "VOLUME BURST CREDIT",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solidfire_volume_burst_iops_credit{sfcluster=~\"$sfcluster\", volume_name=~\"$volume\"}",
     "legendFormat": "{{volume_name}} - burst credits"
    }
   ]
  },
  {
   "title": "VOLUME UTILIZATION",
   "type": "graph",
   "description": "Percentage of allotted IOPS consumed by volume. Note: it's possible to burst to above 100% by making use of burst credits the volume has accumulated.",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "solidfire_volume_utilization{sfcluster=~\"$sfcluster\", volume_name=~\"$volume\"} * 100",
     "legendFormat": "{{volume_name}} - utilization"
    },
    { "expr": "vector(100)", "legendFormat": "max" }
   ]
  },
  {
   "title": "VOLUME ACTUAL IOPS",
   "type": "graph",
   "description": "The current actual IOPS for the volume in the last 500 milliseconds",
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "solidfire_volume_actual_iops{sfcluster=~\"$sfcluster\", volume_name=~\"$volume\"}",
     "legendFormat": "{{volume_name}} - actual iops"
    }
   ]
  },
  {
   "title": "VOLUME IOP SIZE",
   "type": "graph",
   "description": "The average size in bytes of recent I/O to the volume in the last 500 milliseconds.",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "solidfire_volume_average_iop_size_bytes{sfcluster=~\"$sfcluster\", volume_name=~\"$volume\"}",
     "legendFormat": "{{volume_name}} - iop size"
    }
   ]
  },
  {
   "title": "VOLUME CLIENT QUEUE DEPTH",
   "type": "graph",
   "description": "The number of outstanding read and write operations to the volume.",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solidfire_volume_client_queue_depth{sfcluster=~\"$sfcluster\", volume_name=~\"$volume\"}",
     "legendFormat": "{{volume_name}} - queue depth"
    }
   ]
  },
  {
   "title": "VOLUME THROTTLE",
   "type": "graph",
   "description": "Represents how much the system is throttling clients below their maxIOPS because of replication of data, transient errors, and snapshots taken.",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "solidfire_volume_throttle{sfcluster=~\"$sfcluster\", volume_name=~\"$volume\"} * 100",
     "legendFormat": "{{volume_name}} - throttle"
    }
   ]
  },
  {
   "title": "VOLUME UNALIGNED I/O",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(solidfire_volume_unaligned_reads_total{sfcluster=~\"$sfcluster\", volume_name=~\"$volume\"}[$interval])",
     "legendFormat": "{{volume_name}} - unaligned reads"
    },
    {
     "expr": "rate(solidfire_volume_unaligned_writes_total{sfcluster=~\"$sfcluster\", volume_name=~\"$volume\"}[$interval])",
     "legendFormat": "{{volume_name}} - unaligned writes"
    }
   ]
  }
 ]
}
{
 "title": "Volume QoS - $volume",
 "panels": [
  {
   "title": "$volume - BELOW MIN IOPS PERCENTAGE",
   "type": "heatmap",
   "targets": [
    {
     "expr": "sum by(le, volume_name) (rate(solidfire_volume_qos_below_min_iops_percentage_bucket{sfcluster=~\"$sfcluster\",volume_name=~\"$volume\"}[$interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "$volume - MIN TO MAX IOPS PERCENTAGE",
   "type": "heatmap",
   "targets": [
    {
     "expr": "sum by(le, volume_name) (rate(solidfire_volume_qos_min_to_max_iops_percentage_bucket{sfcluster=~\"$sfcluster\",volume_name=~\"$volume\"}[$interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "$volume - READ BLOCK SIZES BYTES",
   "type": "heatmap",
   "targets": [
    {
     "expr": "sum by(le, volume_name) (rate(solidfire_volume_qos_read_block_sizes_bytes_bucket{sfcluster=~\"$sfcluster\",volume_name=~\"$volume\"}[$interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "$volume - WRITE BLOCK SIZES BYTES",
   "type": "heatmap",
   "targets": [
    {
     "expr": "sum by(le, volume_name) (rate(solidfire_volume_qos_write_block_sizes_bytes_bucket{sfcluster=~\"$sfcluster\",volume_name=~\"$volume\"}[$interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "$volume - TARGET UTILIZATION PERCENTAGE",
   "type": "heatmap",
   "targets": [
    {
     "expr": "sum by(le, volume_name) (rate(solidfire_volume_qos_target_utilization_percentage_bucket{sfcluster=~\"$sfcluster\",volume_name=~\"$volume\"}[$interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "$volume - THROTTLE PERCENTAGE",
   "type": "heatmap",
   "targets": [
    {
     "expr": "sum by(le, volume_name) (rate(solidfire_volume_qos_throttle_percentage_bucket{sfcluster=~\"$sfcluster\",volume_name=~\"$volume\"}[$interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}